name: 'Terraform'

on:
  push:
    branches:
      - dev  # Trigger on changes to the 'dev' branch
      - sit   # Trigger on changes to the 'sit' branch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/dev' && secrets.AWS_ASSUME_ROLE_DEV || secrets.AWS_ASSUME_ROLE_SIT }}  
          aws-region: ${{ vars.AWS_REGION }}  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  

      - name: Terraform Init
        run: terraform init
        working-directory: test_glue/  # Specify your Terraform folder

      - name: Terraform Plan
        run: terraform plan
        working-directory: test_glue/  # Specify your Terraform folder

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: test_glue/  # Specify your Terraform folder
