name: Terraform reusable workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      TF_WORKSPACE:
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ inputs.AWS_REGION }}
      TF_WORKSPACE: ${{ inputs.TF_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_DEV }}  # The role ARN to assume
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
          terraform init -input=false
          echo "TF Provider now initialized"
          echo "-------------------------------------"

      - name: Terraform Format
        id: fmt
        run: |
          cd terraform
          terraform fmt

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform
          terraform apply -input=false -auto-approve
