name: AWS-as-Code-for-test
run-name: "Requester (${{ github.actor }}) - ${{ github.event.ref }} - ${{ github.event.head_commit.message }}"
on:
  pull_request:
    branches:
      - dev  

jobs:
  terraform_job:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      env: test
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_WORKSPACE: test
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE_DEV }}  