name: AWS-as-Code-for-test
run-name: "Requester (${{ github.actor }}) - ${{ github.event.ref }} - ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - dev
      - sit  # Add the sit branch if needed

jobs:
  terraform_job:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      env: ${{ github.ref == 'refs/heads/dev' && 'test' || 'sit' }}  # Set environment based on the branch
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_WORKSPACE: ${{ github.ref == 'refs/heads/dev' && 'test' || 'sit' }}  # Adjust workspace based on the branch
    secrets:
      AWS_ASSUME_ROLE: ${{ github.ref == 'refs/heads/dev' && secrets.AWS_ASSUME_ROLE_DEV || secrets.AWS_ASSUME_ROLE_SIT }}  # Use different secrets based on the branch
